### ISSUE TITLE
error: [Errno 10060] A connection attempt failed

### ISSUE THREAD

**Issue by rockmodi** [johnjreiser/chupaESRI#5]
I am getting  an error socket.gaierror: [Errno 11004] get addrinfo failed.

The input url parameter is - 
"https://server.arcgisonline.com/ArcGIS/rest/services/Specialty/Soil_Survey_Map/MapServer/0/?f=pjson"

I have also tried from IP address but getting the error - "error: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond"

**Comment by johnjreiser** [comment]
./chupaESRI.py https://server.arcgisonline.com/ArcGIS/rest/services/Specialty/Soil_Survey_Map/MapServer/0/query "host=localhost dbname=test user=dba" "public.ssurgo"
Works - in that it can connect - but currently throws an error because it cannot determine OBJECTID range. Looks like the service is not performing the statistics as expected. 

I'd be happy to help with this further if it's still needed, but because I can't recreate the original error, I'm going to close this.
